services:

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS= boliviapunto.duckdns.org
      - TOKEN=884f5d7-73eb-4b27-91e0-22a4bf9d30c3
    volumes:
      - ./duckdns/config:/config
    restart: unless-stopped
